name: Cloud Resume Frontend

run-name: Deploy to AWS by @${{ github.actor }}

on: 
  push:
    branches:
      - main


jobs:
    terraform_plan:
        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: ./

        permissions:
            id-token: write # This is required for requesting the JWT
            contents: read  # This is required for actions/checkout
        
        steps:
            - name: Git clone the repository
              uses: actions/checkout@v3
    
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
                role-duration-seconds: 900
                aws-region: us-east-1
    
            - name: Use Terraform 1.5.7
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.5.7
            
            # - name: Initialize Terraform
            #   run: terraform init
    
            - name: Terraform Plan
              run: |
                terraform init
                terraform plan

    terraform_apply:
        needs: ['terraform_plan']
    
        runs-on: ubuntu-latest
    
        environment: 'dev'
    
        defaults:
            run:
                working-directory: ./
    
        permissions:
            id-token: write # This is required for requesting the JWT
            contents: read  # This is required for actions/checkout
        
        steps:
          - name: Git clone the repository
            uses: actions/checkout@v3
    
          - name: configure aws credentials
            uses: aws-actions/configure-aws-credentials@v3
            with:
                role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
                role-duration-seconds: 900
                aws-region: us-east-1
    
          - name: Use Terraform 1.5.7
            uses: hashicorp/setup-terraform@v2
            with:
                terraform_version: 1.5.7
            
            # - name: Initialize Terraform
            #   run: terraform init
    
          - name: Terraform Apply
            run: |
                terraform init
                terraform apply -auto-approve
            
        