name: Cloud Resume Frontend

run-name: Deploy to AWS by @${{ github.actor }}

on: 
  push:
    branches:
      - main


jobs:
    terraform_plan:
        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: ./

        permissions:
            id-token: write # This is required for requesting the JWT
            contents: read  # This is required for actions/checkout
        
        steps:
            - name: Git clone the repository
              uses: actions/checkout@v3
    
            - name: configure aws credentials
              id: creds
              uses: aws-actions/configure-aws-credentials@v3
              with:
                role-to-assume: ${{ secrets.ROLE_TO_ASSUME_GLOBAL }}
                role-duration-seconds: 900
                aws-region: us-east-1

            - name: export credentials
              run: |
                export AWS_ACCESS_KEY_ID="${steps.creds.outputs.aws-access-key-id}"
                export AWS_SECRET_ACCESS_KEY="${steps.creds.outputs.aws-secret-access-key}"
                export AWS_SESSION_TOKEN="${steps.creds.outputs.aws-session-token}" 
                export AWS_PROFILE="global"
    
            - name: Use Terraform 1.5.7
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.5.7
    
            - name: Terraform init
              run: |
                terraform init
                terraform workspace select -or-create=true dev
                terraform plan

            # - name: configure aws credentials
            #   uses: aws-actions/configure-aws-credentials@v3
            #   with:
            #     role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
            #     role-duration-seconds: 900
            #     aws-region: us-east-1                
            
            # - name: Terraform plan
            #   run : |
            #     terraform workspace select -or-create=true dev
            #     terraform plan

    terraform_apply:
        needs: ['terraform_plan']
    
        runs-on: ubuntu-latest
    
        environment: 'dev'
    
        defaults:
            run:
                working-directory: ./
    
        permissions:
            id-token: write # This is required for requesting the JWT
            contents: read  # This is required for actions/checkout
        
        steps:
          - name: Git clone the repository
            uses: actions/checkout@v3
    
          - name: configure aws credentials
            uses: aws-actions/configure-aws-credentials@v3
            with:
                role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
                role-duration-seconds: 900
                aws-region: us-east-1
    
          - name: Use Terraform 1.5.7
            uses: hashicorp/setup-terraform@v2
            with:
                terraform_version: 1.5.7
            
            # - name: Initialize Terraform
            #   run: terraform init
    
          - name: Terraform Apply
            run: | 
                terraform init
                terraform workspace select -or-create=true dev
                terraform apply -auto-approve
            
        